name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
